### ISSUE TITLE
historique

### ISSUE THREAD

**Issue by Wizz1337** [NotPunchnox/punchnox-grabber#1]
il faut que tu **taskill** **chrome** sinon ta pas lhistorique

**Comment by Kalvelign** [comment]
[](url)
![unknown](https://user-images.githubusercontent.com/74380213/117887633-b3ca3700-b2b9-11eb-9343-a9d1b3e42f96.png)

**Comment by spookycheekybreeky** [comment]
ok

**Comment by Chikimaro** [comment]
![image](https://user-images.githubusercontent.com/49518807/118124417-12d89a80-b3e5-11eb-8226-6a9ca31b6ff4.png)
